name: Push to Fasthosts (Final Strike)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'csh3391309'
          server: 'sftp.ashadu.me'
          port: 22
          ssh_private_key: ${{ secrets.FTP_PASSWORD }} 
          # Note: Even though it says 'private_key', this action accepts a password here.
          local_path: './*'
          remote_path: '/htdocs'
          delete_remote_files: false
