name: Push to Fasthosts (Final Strike)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FTP_PASSWORD }}
          ARGS: "-rlgoDzvc -i --delete -e 'ssh -o StrictHostKeyChecking=no'"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          TARGET: "htdocs/"
